data:
  pubmed_cardio_hf_data_id: "hasnat79/pubmed25_cardio"
  start_idx: 0 # modify this index as needed
  end_idx: 100 # modify this index as needed
  finetune_dataset_path: "/scratch/group/instalearn/InstaLearn/src/finetuning_datasets/llama3B_cardio_finetune_dataset_20_abstracts" #modify this path as needed

model: 
  model_name : "llama3B"
  teacher_model_id: "meta-llama/Llama-3.2-3B-Instruct" # modify this path as needed
  student_model_id: "meta-llama/Llama-3.2-3B-Instruct" # modify this path as needed
  checkpoint_dir: "../checkpoints/llama3B_cardio" #modify this path as needed

train:
  train_student: true 
  # evaluate_student: true 
  evaluation_results_path: "evaluation_results/llama3B_cardio_evaluation_results_abstracts_0_20.json" #modify this path as needed
  epochs: 1